services:
  api:
    image: ghcr.io/aaryandhakal22/online-api:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - TRUST_PROXY=1
    env_file:
      - .env
    container_name: quicc_online_backend
    restart: always
    ports:
      - "1323:1323"
    volumes:
      - sqlite_data:/data
    depends_on:
      redis:
        condition: service_healthy

  proxy:
    image: ghcr.io/aaryandhakal22/online-nginx:latest
    container_name: quicc_online_proxy
    restart: unless-stopped
    depends_on:
      certbot_init:
        condition: service_completed_successfully
      api:
        condition: service_started
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot_init:
    image: certbot/dns-cloudflare:latest
    container_name: quicc_certbot_init
    env_file:
      - .env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_logs:/var/log/letsencrypt
      - ./certbot.sh:/certbot.sh:ro
    entrypoint: /certbot.sh
    command: ["init"]
      


  certbot_renew:
    image: certbot/dns-cloudflare:latest
    container_name: quicc_certbot_renew
    restart: unless-stopped
    depends_on:
      certbot_init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_logs:/var/log/letsencrypt
      - ./certbot.sh:/certbot.sh:ro
    entrypoint: /certbot.sh
    command: ["renew"]

  redis:
    container_name: quicc_online_redis
    restart: always
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]


volumes:
  letsencrypt:
  letsencrypt_logs:
  sqlite_data:
