services:
  api:
    image: ghcr.io/quiccpos/online-api:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - TRUST_PROXY=1
    env_file:
      - .env
    container_name: quicc_online_backend
    restart: always
    ports:
      - "1323:1323"
    depends_on:
      redis:
        condition: service_healthy


  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: quicc_certbot
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
      - letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh -c "sleep infinity"

  proxy:
    image: ghcr.io/quiccpos/online-nginx:latest
    container_name: quicc_online_proxy
    restart: unless-stopped
    depends_on:
      certbot_init:
        condition: service_completed_successfully
      backend:
        condition: service_started
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api 

  certbot_init:
    image: certbot/certbot:latest
    container_name: quicc_certbot_init
    env_file:
      - .env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_logs:/var/log/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      set -e;
      mkdir -p /run/secrets;
      printf "%s" "$${CF_API_TOKEN}" > /run/secrets/cf_api_token;
      chmod 600 /run/secrets/cf_api_token;
      if [ -e /etc/letsencrypt/live/$${DOMAIN}/fullchain.pem ]; then
        echo "Certificate already exists, skipping certbot";
        exit 0;
      fi;
      certbot certonly
      --non-interactive
      --agree-tos
      --email $${LE_EMAIL}
      --dns-cloudflare
      --dns-cloudflare-credentials /run/secrets/cf_api_token
      --dns-cloudflare-propagation-seconds 20
      -d "$${DOMAIN}"
      -d "*.$${DOMAIN}";


  certbot_renew:
    image: certbot/dns-cloudflare:latest
    container_name: quicc_certbot_renew
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt_logs:/var/log/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      set -e;
      mkdir -p /run/secrets;
      printf "%s" "$${CF_API_TOKEN}" > /run/secrets/cf_api_token;
      chmod 600 /run/secrets/cf_api_token;
      echo "Starting certbot renew";
      while :; do
        certbot renew
        --non-interactive

        --email $${LE_EMAIL}
        --dns-cloudflare
        --dns-cloudflare-credentials /run/secrets/cf_api_token
        --dns-cloudflare-propagation-seconds 20;
        --deploy-hook "nginx -s reload || true";
        sleep 12h;
      done;

  redis:
    container_name: quicc_online_redis
    restart: always
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]


volumes:
  letsencrypt:
  letsencrypt_logs:
  letsencrypt_www:
