services:
  api:
    image: ghcr.io/quiccpos/online-api:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    env_file:
      - .env
    container_name: quicc_online_backend
    restart: always
    ports:
      - "1323:1323"
    depends_on:
      redis:
        condition: service_healthy


  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: quicc_certbot
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
      - letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh -c "sleep infinity"

  proxy:
    image: ghcr.io/quiccpos/online-nginx:latest
    container_name: quicc_online_proxy
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - api 

  redis:
    container_name: quicc_online_redis
    restart: always
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]


volumes:
  letsencrypt:
