server {
    listen 80;

    server_name _;

    return 301 https://$host$request_uri;
}

server {
  listen 443 ssl ;
  http2 on;
  server_name _;


  ssl_certificate /etc/letsencrypt/live/ingest.quiccpos.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/ingest.quiccpos.com/privkey.pem;

  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;


  # Cloudflare real IP(if you want)
  real_ip_header CF-Connecting-IP;
  include /etc/nginx/conf.d/cloudflare-realip.conf;

  # Your static site
  root /usr/share/nginx/html;
  index index.html;

  # BLOCKING SCANNER TARGET 

  error_page 404 /error404.html;
  location = /error404.html {
    internal;
  }

  error_page 418 /error418.html;
  location = /error418.html {
    internal;
  }

  # Blocking dotfile
  location ~ /\. {
    return 418;
  }

  # Block common secret/config/backup extensions
  location ~* \.(?:env|ini|log|bak|old|swp|sql|sqlite|yml|yaml|toml|key|pem|p12|crt|conf)$ {
      return 418;
  }

  location ~* \.php(?:$|/) {
      return 418;
  }


  location /api/ {
      proxy_pass http://api:1323;   # docker service name or upstream

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;

      # timeouts (tune as needed)
      proxy_connect_timeout 5s;
      proxy_read_timeout 60s;
      proxy_send_timeout 60s;

      proxy_intercept_errors on;
  }

  # Serve static files (and SPA fallback if you want)
  location / {
    try_files $uri $uri/ /index.html;
  }

}

