// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

type ApiKey struct {
	ID     string `json:"id"`
	Key    string `json:"key"`
	Status string `json:"status"`
}

type Order struct {
	ID          string `json:"id"`
	Payload     string `json:"payload"`
	DateCreated string `json:"date_created"`
	CreatedAt   string `json:"created_at"`
}
