// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
)

const activateKey = `-- name: ActivateKey :exec
UPDATE api_keys SET status = 'active' WHERE id = ?1
`

func (q *Queries) ActivateKey(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.activateKeyStmt, activateKey, id)
	return err
}

const createKey = `-- name: CreateKey :exec
INSERT INTO api_keys (id, key, status) VALUES (?1, ?2, ?3)
`

type CreateKeyParams struct {
	ID     string `json:"id"`
	Key    string `json:"key"`
	Status string `json:"status"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) error {
	_, err := q.exec(ctx, q.createKeyStmt, createKey, arg.ID, arg.Key, arg.Status)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, payload, date_created) 
VALUES (?1, ?2, ?3) 
RETURNING id
`

type CreateOrderParams struct {
	ID          string `json:"id"`
	Payload     string `json:"payload"`
	DateCreated string `json:"date_created"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (string, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder, arg.ID, arg.Payload, arg.DateCreated)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deactivateKey = `-- name: DeactivateKey :exec
UPDATE api_keys Set status = 'inactive' WHERE status = 'active'
`

func (q *Queries) DeactivateKey(ctx context.Context) error {
	_, err := q.exec(ctx, q.deactivateKeyStmt, deactivateKey)
	return err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM api_keys WHERE id = ?1
`

func (q *Queries) DeleteKey(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteKeyStmt, deleteKey, id)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = ?1
`

func (q *Queries) DeleteOrder(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteOrderStmt, deleteOrder, id)
	return err
}

const getActiveKey = `-- name: GetActiveKey :one
SELECT id, "key", status FROM api_keys WHERE status = 'active' ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetActiveKey(ctx context.Context) (ApiKey, error) {
	row := q.queryRow(ctx, q.getActiveKeyStmt, getActiveKey)
	var i ApiKey
	err := row.Scan(&i.ID, &i.Key, &i.Status)
	return i, err
}

const getKeyByID = `-- name: GetKeyByID :one
SELECT id, "key", status FROM api_keys WHERE id = ?1
`

func (q *Queries) GetKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.queryRow(ctx, q.getKeyByIDStmt, getKeyByID, id)
	var i ApiKey
	err := row.Scan(&i.ID, &i.Key, &i.Status)
	return i, err
}

const getLatestOrder = `-- name: GetLatestOrder :one
SELECT id, payload, date_created, created_at FROM orders ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestOrder(ctx context.Context) (Order, error) {
	row := q.queryRow(ctx, q.getLatestOrderStmt, getLatestOrder)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.DateCreated,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, payload, date_created, created_at FROM orders WHERE id = ?1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.queryRow(ctx, q.getOrderByIDStmt, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.DateCreated,
		&i.CreatedAt,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT id, payload, date_created, created_at FROM orders
`

func (q *Queries) GetOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.query(ctx, q.getOrdersStmt, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.DateCreated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimedKey = `-- name: GetPrimedKey :one
SELECT id, "key", status FROM api_keys WHERE status = 'primed' ORDER BY id ASC LIMIT 1
`

func (q *Queries) GetPrimedKey(ctx context.Context) (ApiKey, error) {
	row := q.queryRow(ctx, q.getPrimedKeyStmt, getPrimedKey)
	var i ApiKey
	err := row.Scan(&i.ID, &i.Key, &i.Status)
	return i, err
}

const getTodaysOrders = `-- name: GetTodaysOrders :many
SELECT id, payload, date_created, created_at FROM orders WHERE date_created = strftime('%Y-%m-%d', 'now')
`

func (q *Queries) GetTodaysOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.query(ctx, q.getTodaysOrdersStmt, getTodaysOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.DateCreated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unprimeAll = `-- name: UnprimeAll :exec
UPDATE api_keys SET status = 'inactive' WHERE status = 'primed'
`

func (q *Queries) UnprimeAll(ctx context.Context) error {
	_, err := q.exec(ctx, q.unprimeAllStmt, unprimeAll)
	return err
}
