// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package models

import (
	"context"
)

const activateKey = `-- name: ActivateKey :exec
UPDATE api_keys SET status = 'active' WHERE id = ?1
`

func (q *Queries) ActivateKey(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.activateKeyStmt, activateKey, id)
	return err
}

const createKey = `-- name: CreateKey :exec
INSERT INTO api_keys (id, key, status) VALUES (?1, ?2, ?3)
`

type CreateKeyParams struct {
	ID     string `json:"id"`
	Key    string `json:"key"`
	Status string `json:"status"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) error {
	_, err := q.exec(ctx, q.createKeyStmt, createKey, arg.ID, arg.Key, arg.Status)
	return err
}

const deactivateKey = `-- name: DeactivateKey :exec
UPDATE api_keys SET status = 'inactive' WHERE id = ?1
`

func (q *Queries) DeactivateKey(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deactivateKeyStmt, deactivateKey, id)
	return err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM api_keys WHERE id = ?1
`

func (q *Queries) DeleteKey(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteKeyStmt, deleteKey, id)
	return err
}

const getActiveKey = `-- name: GetActiveKey :one
SELECT id, "key", status FROM api_keys WHERE status = 'active' ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetActiveKey(ctx context.Context) (ApiKey, error) {
	row := q.queryRow(ctx, q.getActiveKeyStmt, getActiveKey)
	var i ApiKey
	err := row.Scan(&i.ID, &i.Key, &i.Status)
	return i, err
}

const getKeyByID = `-- name: GetKeyByID :one
SELECT id, "key", status FROM api_keys WHERE id = ?1
`

func (q *Queries) GetKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.queryRow(ctx, q.getKeyByIDStmt, getKeyByID, id)
	var i ApiKey
	err := row.Scan(&i.ID, &i.Key, &i.Status)
	return i, err
}

const getPrimedKey = `-- name: GetPrimedKey :one
SELECT id, "key", status FROM api_keys WHERE status = 'primed' ORDER BY id ASC LIMIT 1
`

func (q *Queries) GetPrimedKey(ctx context.Context) (ApiKey, error) {
	row := q.queryRow(ctx, q.getPrimedKeyStmt, getPrimedKey)
	var i ApiKey
	err := row.Scan(&i.ID, &i.Key, &i.Status)
	return i, err
}

const unprimeAll = `-- name: UnprimeAll :exec
UPDATE api_keys SET status = 'inactive' WHERE status = 'primed'
`

func (q *Queries) UnprimeAll(ctx context.Context) error {
	_, err := q.exec(ctx, q.unprimeAllStmt, unprimeAll)
	return err
}
