// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	ActivateKey(ctx context.Context, id string) error
	CreateKey(ctx context.Context, arg CreateKeyParams) error
	DeactivateKey(ctx context.Context) error
	DeleteKey(ctx context.Context, id string) error
	GetActiveKey(ctx context.Context) (ApiKey, error)
	GetKeyByID(ctx context.Context, id string) (ApiKey, error)
	GetPrimedKey(ctx context.Context) (ApiKey, error)
	UnprimeAll(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
